debug: false
language: ru
database: sqlite # mysql or sqlite
mysql:
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: admin
settings:
    warm: 2
    max_symbols: 10
    min_symbols: 3
    default_max: 30
    max_upgrade: 50
    cost: 100 #Cost of creating clan. Set 0 to disable.
    clan_regex: '[а-яА-Яa-zA-Z0-9]*'